### ISSUE TITLE
 Implementing Organization Page for Uptane Repository

### ISSUE THREAD

**Issue by Abhijay007** [uptane/.github#1]
Description:

Currently, the Uptane repository lacks an organizational page, which has been a topic of discussion within our community for some time. Therefore, it is imperative to implement one. The organizational page should provide a basic overview of Uptane, including information about our social media presence, partnered organizations, projects within the Uptane ecosystem, and a brief summary about the community and contributing to the ecosystem.

To gather inspiration and ideas, I have attached a few resources:

- [Layer5IO GitHub Organization](https://github.com/layer5io)
- [Moja Global GitHub Organization](https://github.com/moja-global)
- [Microsoft GitHub Organization](https://github.com/microsoft)

**Comment by jhdalek55** [comment]
I think this can be closed with the merging of PR#2.

**Comment by Abhijay007** [comment]
> I think this can be closed with the merging of PR#2.

Thanks @jhdalek55, closed via #2

**Comment by Abhijay007** [comment]
> I think this can be closed with the merging of PR#2.

Thanks @jhdalek55, closed via https://github.com/uptane/.github/pull/2
